#!python
# ruff: noqa: F821

import os

Import("env")
Import("env_modules")

env_avif = env_modules.Clone()

# Minimum target platform versions.
if "ios_min_version" not in env_avif:
    env_avif["ios_min_version"] = "11.0"
if "macos_deployment_target" not in env_avif:
    env_avif["macos_deployment_target"] = "11.0"

# Dependencies
for tool in ["cmake", "aom", "yuv", "avif"]:
    env_avif.Tool(tool, toolpath=["tools"])

deps = []
# For universal binaries, we first need to build the libraries separately,
# then join them together using lipo.
if env["platform"] == "macos" and env["arch"] == "universal":
    build_envs = {
        "x86_64": env_avif.Clone(),
        "arm64": env_avif.Clone(),
    }
    arch_aom = []
    arch_avif = []
    arch_yuv = []
    for arch in build_envs:
        benv = build_envs[arch]
        benv["arch"] = arch
        arch_aom.extend(benv.BuildAOM())
        arch_yuv.extend(benv.BuildLibYUV())
        arch_avif.extend(benv.BuildLibAvif(arch_aom, arch_yuv))

    # Join libraries using lipo.
    for targets in [arch_aom, arch_yuv, arch_avif]:
        libs = list(filter(lambda f: str(f).endswith(".a"), targets))
        path = "#bin/thirdparty/lipo"
        os.makedirs(env_avif.Dir(path).abspath, exist_ok=True)
        lipo_action = "lipo $SOURCES -create -output $TARGET"
        lib = env.Command(
            env_avif.File("{}/{}".format(path, os.path.basename(libs[0].abspath))),
            libs,
            lipo_action,
        )
        env_avif.Depends(lib, libs)
        env_avif.Append(LIBS=lib)
        deps.extend(lib)
    env_avif.Append(CPPPATH=[env_avif["AOM_INCLUDE"]])
    env_avif.Append(CPPPATH=[env_avif["YUV_INCLUDE"]])
    env_avif.Append(CPPPATH=[env_avif["AVIF_INCLUDE"]])
else:
    # Make our dependencies
    aom = env_avif.BuildAOM()
    yuv = env_avif.BuildLibYUV()
    avif = env_avif.BuildLibAvif(aom, yuv)
    deps = aom + yuv + avif

deps.reverse()

module_obj = []
env_avif.add_source_files(module_obj, "*.cpp")

env.modules_sources += module_obj

# Needed to force rebuilding the module files when the thirdparty library is updated.
env.Depends(module_obj, deps)

# Add libs to godot binary linkflags
lib_ext = ".lib" if env.msvc else ".a"
env.Append(LIBS=list(filter(lambda f: str(f).endswith(lib_ext), deps)))
